using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WindEditor
{
    public enum BokoblinHeldItem
    {
        Unlit_Torch,
        Machete_1,
        Lit_Torch,
        Machete_2
    }

    public enum BokoblinType
    {
        Wandering,
        Unknown_1,
        Unknown_2,
        Hiding_in_a_Pot,
        Guarding,
        Being_Carried_by_a_Kargaroc,
        Search_Light_Operator,
        Jumping,
        Guarding_and_Yawning = 10,
        Pink_Bokoblin_with_Telescope,
        Debug = 15
    }

    public enum ChestType
    {
        Light_wood,
        Dark_wood,
        Metal,
        Big_Key
    }

    public enum ChestBehavior
    {
        Normal,
        Spawn_when_a_switch_is_set,
        Spawn_when_all_enemies_are_defeated,
        Visible_but_unopenable_until_a_switch_is_set,
        Transparent_until_a_switch_is_set,
        Apply_gravity,
        Spawn_when_a_Wind_Waker_song_is_played,
        Uses_extra_open_flag,
        Uses_extra_open_flag_and_spawns_when_a_switch_is_set
    }

    public enum FoliageType
    {
        Grass,
        Tree,
        White_Flower,
        Pink_Flower
    }

    public enum GohdanComponent
    {
        Head,
        Left_Hand,
        Right_Hand
    }

    public enum ItemID
    {
        Heart = 0,
        Green_Rupee = 1,
        Blue_Rupee = 2,
        Yellow_Rupee_1 = 3,
        Red_Rupee = 4,
        Purple_Rupee = 5,
        Orange_Rupee = 6,
        Piece_of_Heart = 7,
        Heart_Container = 8,
        Small_Magic_Jar = 9,
        Large_Magic_Jar = 10,
        Bombs_5 = 11,
        Bombs_10 = 12,
        Bombs_20 = 13,
        Bombs_30 = 14,
        Silver_Rupee = 15,
        Arrows_10 = 16,
        Arrows_20 = 17,
        Arrows_30 = 18,
        Green_Rupee_0 = 19,
        Blue_Rupee_2 = 20,
        Small_Key = 21,
        Fairy = 22,
        Yellow_Rupee_2 = 26,
        Joy_Pendant = 31,
        Telescope = 32,
        Tingle_Tuner = 33,
        Wind_Waker = 34,
        Pictobox = 35,
        Spoils_Bag = 36,
        Grappling_Hook = 37,
        Deluxe_Pictobox = 38,
        Heros_Bow = 39,
        Power_Bracelets = 40,
        Iron_Boots = 41,
        Magic_Armor = 42,
        Bait_Bag = 44,
        Boomerang = 45,
        Hookshot = 47,
        Delivery_Bag = 48,
        Bombs = 49,
        Heros_Clothes = 50,
        Skull_Hammer = 51,
        Deku_Leaf = 52,
        Fire_and_Ice_Arrows = 53,
        Light_Arrows = 54,
        Heros_New_Clothes = 55,
        Heros_Sword = 56,
        Master_Sword_Powerless = 57,
        Master_Sword_Half_Power = 58,
        Heros_Shield = 59,
        Mirror_Shield = 60,
        Heros_Sword_Dropped = 61,
        Master_Sword_Full_Power = 62,
        Piece_of_Heart_2 = 63,
        Heros_Charm = 67,
        Green_Rupee_10 = 68,
        Skull_Necklace = 69,
        Boko_Baba_Seed = 70,
        Golden_Feather = 71,
        Knights_Crest = 72,
        Red_Chu_Jelly = 73,
        Green_Chu_Jelly = 74,
        Blue_Chu_Jelly = 75,
        Dungeon_Map = 76,
        Compass = 77,
        Big_Key = 78,
        Green_Rupee_11 = 79,
        Empty_Bottle = 80,
        Red_Potion = 81,
        Green_Potion = 82,
        Blue_Potion = 83,
        Elixir_Soup = 85,
        Bottled_Water = 86,
        Bottled_Fairy = 87,
        Bottled_Forest_Firefly = 88,
        Bottled_Forest_Water = 89,
        Triforce_Shard_1 = 97,
        Triforce_Shard_2 = 98,
        Triforce_Shard_3 = 99,
        Triforce_Shard_4 = 100,
        Triforce_Shard_5 = 101,
        Triforce_Shard_6 = 102,
        Triforce_Shard_7 = 103,
        Triforce_Shard_8 = 104,
        Nayrus_Pearl = 105,
        Dins_Pearl = 106,
        Farores_Pearl = 107,
        Winds_Requiem = 109,
        Ballad_of_Gales = 110,
        Command_Melody = 111,
        Earth_Gods_Lyric = 112,
        Wind_Gods_Aria = 113,
        Song_of_Passing = 114,
        Sail = 120,
        Deciphered_Triforce_Chart_8 = 121,
        Deciphered_Triforce_Chart_7 = 122,
        Deciphered_Triforce_Chart_6 = 123,
        Deciphered_Triforce_Chart_5 = 124,
        Deciphered_Triforce_Chart_4 = 125,
        Deciphered_Triforce_Chart_3 = 126,
        Deciphered_Triforce_Chart_2 = 127,
        Deciphered_Triforce_Chart_1 = 128,
        Bait = 130,
        Hyoi_Pear = 131,
        Town_Flower = 140,
        Sea_Flower = 141,
        Exotic_Flower = 142,
        Heros_Flag = 143,
        Big_Catch_Flag = 144,
        Big_Sale_Flag = 145,
        Pinwheel = 146,
        Sickle_Moon_Flag = 147,
        Skull_Tower_Idol = 148,
        Fountain_Idol = 149,
        Postman_Statue = 150,
        Shop_Guru_Statue = 151,
        Fathers_Letter = 152,
        Note_to_Mom = 153,
        Maggies_Letter = 154,
        Moblins_Letter = 155,
        Cabana_Deed = 156,
        Complimentary_ID = 157,
        FillUp_Coupon = 158,
        Legendary_Pictograph = 159,
        Dragon_Tingle_Statue = 163,
        Forbidden_Tingle_Statue = 164,
        Goddess_Tingle_Statue = 165,
        Earth_Tingle_Statue = 166,
        Wind_Tingle_Statue = 167,
        Hurricane_Spin = 170,
        Wallet_1000_Rupees = 171,
        Wallet_5000_Rupees = 172,
        Bomb_Bag_60 = 173,
        Bomb_Bag_99 = 174,
        Quiver_60_Arrows = 175,
        Quiver_99_Arrows = 176,
        Increased_Magic_Power = 178,
        Tingle_Statue_Reward_50_Rupees_per_statue_1 = 179,
        Tingle_Statue_Reward_50_Rupees_per_statue_2 = 180,
        Tingle_Statue_Reward_50_Rupees_per_statue_3 = 181,
        Tingle_Statue_Reward_50_Rupees_per_statue_4 = 182,
        Tingle_Statue_Reward_50_Rupees_per_statue_5 = 183,
        Rupees_for_Finding_Tingle_Statues = 184,
        Submarine_Chart = 194,
        Beedles_Chart = 195,
        Platform_Chart = 196,
        Light_Ring_Chart = 197,
        Secret_Cave_Chart = 198,
        Sea_Hearts_Chart = 199,
        Island_Hearts_Chart = 200,
        Great_Fairy_Chart = 201,
        Octo_Chart = 202,
        INcredible_Chart = 203,
        Treasure_Chart_1 = 204,
        Treasure_Chart_2 = 205,
        Treasure_Chart_3 = 206,
        Treasure_Chart_4 = 207,
        Treasure_Chart_5 = 208,
        Treasure_Chart_6 = 209,
        Treasure_Chart_7 = 210,
        Treasure_Chart_8 = 211,
        Treasure_Chart_9 = 212,
        Treasure_Chart_10 = 213,
        Treasure_Chart_11 = 214,
        Treasure_Chart_12 = 215,
        Treasure_Chart_13 = 216,
        Treasure_Chart_14 = 217,
        Treasure_Chart_15 = 218,
        Ghost_Ship_Chart = 219,
        Tingles_Chart = 220,
        Treasure_Chart_16 = 221,
        Treasure_Chart_17 = 222,
        Treasure_Chart_18 = 223,
        Treasure_Chart_19 = 224,
        Treasure_Chart_20 = 225,
        Treasure_Chart_21 = 226,
        Treasure_Chart_22 = 227,
        Treasure_Chart_23 = 228,
        Treasure_Chart_24 = 229,
        Treasure_Chart_25 = 230,
        Treasure_Chart_26 = 231,
        Treasure_Chart_27 = 232,
        Treasure_Chart_28 = 233,
        Treasure_Chart_29 = 234,
        Treasure_Chart_30 = 235,
        Treasure_Chart_31 = 236,
        Treasure_Chart_32 = 237,
        Treasure_Chart_33 = 238,
        Treasure_Chart_34 = 239,
        Treasure_Chart_35 = 240,
        Treasure_Chart_36 = 241,
        Treasure_Chart_37 = 242,
        Treasure_Chart_38 = 243,
        Treasure_Chart_39 = 244,
        Treasure_Chart_40 = 245,
        Treasure_Chart_41 = 246,
        Triforce_Chart_1 = 247,
        Triforce_Chart_2 = 248,
        Triforce_Chart_3 = 249,
        Triforce_Chart_4 = 250,
        Triforce_Chart_5 = 251,
        Triforce_Chart_6 = 252,
        Triforce_Chart_7 = 253,
        Triforce_Chart_8 = 254,
        No_item = 255
    }
}
